# Generated by Django 5.0.6 on 2024-06-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kms_driven',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_rs',
            field=models.CharField(max_length=50),
        ),
    ]
